/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsconfig = {
  Auth: {
    identityPoolId: "eu-central-1:e890418d-9f6a-4763-9b41-2e04570e81cf",
    region: "eu-central-1",
    userPoolId: "eu-central-1_nAipzRc6Q",
    userPoolWebClientId: "7nb6a6k0kc8e51lqff03basoad",
    oauth: {
      domain: "chirag-social-test.auth.eu-central-1.amazoncognito.com",
      scope: ["email", "profile", "openid"],
      redirectSignIn: window.location.href,
      redirectSignOut: window.location.href,
      responseType: "token", // for Authorization Code Grant
    },
  },
};

// const awsmobile = {
//   aws_project_region: "us-east-1",
//   aws_cognito_identity_pool_id:
//     "us-east-1:e2435bdf-dde4-4315-b2ab-00d44e28052e",
//   aws_cognito_region: "us-east-1",
//   aws_user_pools_id: "us-east-1_FApOOZ5UH",
//   aws_user_pools_web_client_id: "5o74fo9fj17fs05q5r25or0bg1",
//   oauth: {
//     // "domain": "googlefin-dev.auth.us-east-1.amazoncognito.com",
//     // "scope": [
//     //     "phone",
//     //     "email",
//     //     "openid",
//     //     "profile",
//     //     "aws.cognito.signin.user.admin"
//     // ],
//     // "redirectSignIn": "http://localhost:3000/",
//     // "redirectSignOut": "http://localhost:3000/",
//     // "responseType": "code"
//   },
//   federationTarget: "COGNITO_USER_POOLS",
//   aws_cognito_username_attributes: ["EMAIL"],
//   aws_cognito_social_providers: ["GOOGLE"],
//   aws_cognito_signup_attributes: ["EMAIL"],
//   aws_cognito_mfa_configuration: "OFF",
//   aws_cognito_mfa_types: ["SMS"],
//   aws_cognito_password_protection_settings: {
//     passwordPolicyMinLength: 8,
//     passwordPolicyCharacters: [],
//   },
//   aws_cognito_verification_mechanisms: ["EMAIL"],
// };

export default awsconfig;
